#' @title Run compiled commands in the specified environment
#' 
#' @description
#' Executes the commands object in the specified environment by calling 
#' the peudo package which is indexed by the in the commands object key.
#' 
#' @param compiled_commands A commands object generated by compile_commands that
#' can be executed in any specified environment, assuming the variables listed
#' in the commands object are defined in that environment.
#' 
#' @returns NULL
#' @examples
#' expr_ls <- list(substitute(x <- x + 1))
#' 
#' commands_object <- compile_commands(expr_ls)
#' 
#' run_commands(commands_object, environment())
run_commands <- function(compiled_commands, eval_env) {
  
  # get compiled temp lib loaded to the namespace
  compile_path <- system.file("compile", package = "GPUrun")
  temp_installed_path <- file.path(compile_path, INSTALL_LOC)
  library(compiled_commands$key, lib.loc = temp_installed_path,
          character.only = T)
  
  # bind the variables in the compiled_command R object to compiled memory
  eval(parse(text = paste0(compiled_commands$key, 
                           "_bind_vars(compiled_commands$vars, eval_env)")))
  
  # evaluate the commands with parallel compiled code
  eval(parse(text = paste0(compiled_commands$key, "_execute_commands()")))
  
  # update the R variables in the evaluated environment with the 
  # values retrieved from the compiled run of the commands
  # and free the variables in compiled memory
  eval(parse(text = paste0(compiled_commands$key, 
                           "_update_vars(compiled_commands$vars, eval_env)")))
  
  # unload the temporary package
  unloadNamespace(compiled_commands$key)
  
  return(NULL)
}
